todoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_app/urls.py
from django.urls import path, include
from . import views

app_name = 'todo_app'

urlpatterns = [
    # path('', views.home, name='home'),
    # path('details/<int:id>', views.details, name="details"),
    # path('update/<int:id>', views.update, name="update"),
    path('delete/<int:id>', views.delete, name="delete"),
    path('', views.TaskListView.as_view(), name='home'),
    path('details/<int:pk>', views.TaskDetailView.as_view(), name='details'),
    path('update/<int:pk>', views.TaskUpdateView.as_view(), name='update'),
    path('add', views.add_new_todo, name='add')
]

todo_app/models.py
from django.db import models
import datetime

# Create your models here.
class ToDo(models.Model):
    def __str__(self):
        return self.subject
    subject = models.CharField(max_length=100)
    priority = models.IntegerField()
    date = models.DateField(default=datetime.date.today)

todo_app/forms.py
from .models import ToDo
from django import forms

class UpdateForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ['subject', 'priority', 'date']
        

todo_app/views.py
from django.shortcuts import render, redirect
from .models import ToDo
from .forms import UpdateForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.

class TaskListView(ListView):
    model = ToDo
    template_name = 'home.html'
    context_object_name = 'tasks'
    
    
class TaskDetailView(DetailView):
    model = ToDo
    template_name = 'details.html'
    context_object_name = 'task'


class TaskUpdateView(UpdateView):
    model = ToDo
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('subject', 'priority', 'date')
    def get_success_url(self):
        return reverse_lazy('todo_app:details', kwargs={'pk': self.object.id})




def add_new_todo(request):
    if request.method == "POST":
        subject = request.POST['subject']
        priority = request.POST['priority']
        date = request.POST['date']
        tasks = ToDo(subject=subject, priority=priority, date=date)
        tasks.save()
        return redirect('todo_app:home')

# def details(request, id):
#     task = ToDo.objects.get(id=id)
#     return render(request, 'details.html', {"task": task})

# def update(request, id):
#     task = ToDo.objects.get(id=id)
#     if request.method == "POST":
#         task.subject = request.POST['subject']
#         task.priority = request.POST['priority']
#         task.date = request.POST['date']
#         task.save()
#         return redirect('todo_app:home')
#     return render(request, 'update.html', {'task': task})


def delete(request, id):
    if request.method == "POST":
        task = ToDo.objects.get(id=id)
        task.delete()
        return redirect('todo_app:home')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css"
    />
    {% block head %}{% endblock %}
  </head>
  <body>
    <header>
        <nav class="navbar navbar-dark">
            <div class="container-fluid">
            <a class="navbar-brand h1 mr-auto text-white" href="{% url 'todo_app:home' %}">To Do</a>
              <a class="btn btn-success" type="submit" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                  Add New
              </a>
        </div>
          </nav>
    </header>
        
        {% block content %} {% endblock %}
    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>

templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block head %}

<title>{{ task.subject }} - {{ task.priority }}</title>

{% endblock %}
{% block content %}

<div class="container">
<div class="jumbotron jumbotron-fluid p-lg-5" style="position: relative; top: 100px; border-radius: 30px;">
    <div class="container">
      <h1 class="display-4">{{  task.subject }}</h1>
      <p class="lead">{{ task.date }}</p>
  <hr class="my-4">
      <p class="lead">{{ task.priority }}</p>
        
      <div class="row mx-auto mt-lg-5">
        
        <div class="mr-auto" style="position: relative; bottom: 5px; left:80px;">
          <button class="btn btn-outline-danger"  data-toggle="collapse" href="#confirmDelete" role="button" aria-expanded="false" aria-controls="collapseExample">
              Delete</button>
        </div>
    
        <div class="mx-auto" style="position: relative; bottom: 5px;">
            <a href="{% url 'todo_app:update' task.id %}"><button class="btn btn-info">Edit</button></a>
          </div>

    <!-- <form method="POST" action="{% url 'todo_app:update' task.id %}"> -->
        <!-- {% csrf_token %} -->
        <div class="ml-auto" style="position: relative; bottom: 5px; right:80px;">
          <a href="/"><button class="btn btn-warning">In process</button></a>
        </div>
    <!-- </form> -->
    
      </div>
    <br>
      
    </div>

    <div class="collapse" id="confirmDelete">
        <form method="POST" action="{% url 'todo_app:delete' task.id %}">
        {% csrf_token %}
        <div class="alert alert-warning" role="alert">
            Confirm Delete! 
            <button class="btn btn-outline-danger">
                Delete
              </button>
          </div>
        </form>
      </div>

  </div>
</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %} {% load static %} {% block head %}
<!-- <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css"> -->
<title>Home</title>
{% endblock %} {% block content %}
<div class="container-fluid">
  <div class="collapse p-3 mb-5 rounded" id="collapseExample">
    <div class="row">
      <div class="card my-5 col-lg-6 col-md-8  col-sm-10 ml-auto mr-auto text-white bg-dark">
          <div class="card-header mx-auto">Add New To Do</div>
        <div class="card-body">

          <form action="{% url 'todo_app:add' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- {{ form.as_p }} -->
            <div class="form-group">
              <label for="subject">Subject</label>
              <input
                type="text"
                id="subject"
                name="subject"
                class="form-control"
                placeholder="Subject"
              />
            </div>
            <div class="form-group">
              <label for="priority">Priority</label>
              <input
                type="text"
                id="priority"
                name="priority"
                class="form-control"
                placeholder="Priority"
              />
            </div>
            <div class="form-group">
                <label for="date">Date</label>
                <input
                  type="date"
                  id="date"
                  name="date"
                  class="form-control"
                  placeholder="Priority"
                />
              </div>
            <div class="justify-content-end">
              <div class="row mx-auto">
                <div class="mr-auto">
                    <a class="btn btn-danger ml-auto" type='button' data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">Cancel</a>

                </div>
                <div class="ml-auto">
                  <button type="submit" class="btn btn-success">
                    Add New To Do
                  </button>
                </div>
              </div>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>

  <h3 class="mt-5">All To Do's</h3>
  <div class="container-fluid">
    <div class="row px-3 py-3 justify-content-center">

        {%  if not tasks %}

        <div class="alert alert-danger text-lg-center" role="alert">
            <p class='display-4'>There is nothing in To Do's! <br>Add Something!</p>
            <a class="btn btn-success" type="submit" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                Add New
            </a>
          </div>

          {% else %}

        {% for task in tasks reversed %}
        
      <div
        class="card col col-lg-3 col-md-4 col-sm-6 mx-2 my-2 bg-dark text-white"
        style="max-width: 340px; min-width: 340px"
      >
      <a href="{% url 'todo_app:details' task.id %}" style="text-decoration: none;" class="text-white">
        <h4 class="card-header">{{ task.subject }}</h4>
        <div class="card-body">
        <h6 class='card-title disabled'>{{ task.date }}</h6>
          <p class="card-text">{{ task.priority }}</p></a>
          
        </div>
        <div class="card-footer mt-5">
            <div class="row mx-auto">
                
                <div class="mr-auto" style="position: relative; bottom: 20px;">
                  <button class="btn btn-outline-danger" data-toggle="collapse" href="#confirmDelete{{task.id}}" role="button" aria-expanded="false" aria-controls="collapseExample">
                      Delete
                    </button>
                </div>

                
                    <div class="mx-auto" style="position: relative; bottom: 20px;">
                      <a href="{% url 'todo_app:update' task.id %}"><button class="btn btn-info">Edit</button></a>
                    </div>
                    
                
            
                <form method="POST" action="{% url 'todo_app:update' task.id %}">
                    {% csrf_token %}
                <div class="ml-auto" style="position: relative; bottom: 20px;">
                  <button class="btn btn-warning">In process</button>
                </div>
            </form>

                
              </div>

              <div class="collapse" id="confirmDelete{{task.id}}">
                <form method="POST" action="{% url 'todo_app:delete' task.id %}">
                {% csrf_token %}
                <div class="alert alert-warning" role="alert">
                    Confirm Delete! 
                    <button class="btn btn-outline-danger" style='position: relative; left: 45px;'>
                        Delete
                      </button>
                  </div>
                </form>
              </div>

        </div>
      </div>
    

{% endfor %}

{% endif %}

    </div>
  </div>
</div>
{% endblock %}

templates/update.html
{% extends 'base.html' %}

{% block head %}
<title>Update - {{ task.subject }}</title>
{% endblock %}

{% block content %}


<div class="container-fluid">
    <div class="row">
            <div class="card my-5 col-md-6 col-sm-1 ml-auto mr-auto text-white bg-dark">
                <div class="card-header mx-auto">Update - {{ task.subject }}</div>
              <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <!-- {{ form.as_p }} -->

                  <div class="form-group">
                    <label for="subject">Subject</label>
                    <input
                      type="text"
                      id="subject"
                      name="subject"
                      class="form-control"
                      value="{{task.subject}}"
                    />
                  </div>
                  <div class="form-group">
                    <label for="priority">Priority</label>
                    <input
                      type="text"
                      id="priority"
                      name="priority"
                      class="form-control"
                      value="{{ task.priority }}"

                    />
                  </div>
                  <div class="form-group">
                      <label for="date">Date</label>
                      <input
                        type="date"
                        id="date"
                        name="date"
                        class="form-control"
                        placeholder="Priority"
                        value="{{ task.date }}"
                      />
                    </div>
                  <div class="justify-content-end">
                    <div class="row mx-auto">
                      <div class="mr-auto">
                        <a class="btn btn-danger ml-auto" href="/">Cancel</a>
                      </div>
                      <div class="ml-auto">
                        <button type="submit" class="btn btn-warning">
                          UPDATE
                        </button>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
    </div>
</div>

{% endblock %}